function generateISCIHCActivityMovie(img,labels,positiveIndices,IHClabelroi,IHClocation,name,clims,h)
%generateActivityMovie This function generates a movie of the activity with the grid.
% Variables: img: movie stack (not dFoF, but bleach corrected)
%            labels: ISC labels (time x # of roi, 2D)
%            positiveIndices: generated by ISC grid analysis
%            IHClabelroi: IHC labels (time x # of roi, 2D)
%            IHClocation: point indicating IHC location (x,y)
%            name = name of file to output
%            clims: limits of movie for making lighter darker
    if nargin < 5
            clims = [500 10000];
    end
    cmap = colormap('prism');
    if exist('h')
        figure(h)
    else
        figure; 
    end
    imagesc(zeros(800,800)); colormap(gray); truesize;
    for i = 1:size(img,3)
        indx_green = find(labels(i,:)>=1);
        imagesc(img(:,:,i)); caxis(clims); hold on;
        %for j=1:size(positiveIndices,1)
        %plot(positiveIndices(j,1:2:end),positiveIndices(j,2:2:end),'Color','k');
        %end
        if ~isempty(indx_green)
            for j = 1:size(indx_green,2)
                 colors = cmap(mod(labels(i,indx_green(j)),256),:);
                 plot(positiveIndices(indx_green(j),1:2:end),positiveIndices(indx_green(j),2:2:end),'Color',colors);
            end
        end
        
        %%IHCs
        indx_green = find(IHClabelroi(i,:)>=1);
        if ~isempty(indx_green)
            for j = 1:size(indx_green,2)
                temp = indx_green(j);
                if IHClabelroi(i,indx_green(j)) == 999
                    colors = [1 1 1] * 0.7;
                else
                    colors = cmap(mod(IHClabelroi(i,indx_green(j)),256),:);
                end
                drawellipse('Position',IHClocation(temp,:),'SemiAxes',[1 1],'Color',colors,'InteractionsAllowed','none');
            end
        end
        
        M(i) = getframe;
        hold off;
    end

%write video
    if ~isempty(name)
        [~,~,ext] = fileparts(name);
        if strcmp(ext,'.avi')
            v = VideoWriter(name,'Uncompressed AVI');
        elseif strcmp(ext,'.mp4')
            v = VideoWriter(name,'MPEG-4');
            v.Quality = 100;
        end
            
        v.FrameRate = 10;
        open(v);

        for i=1:size(M,2)
            writeVideo(v,M(i).cdata);
        end
        close(v);
    end
end


function generateActivityMovie(img, thrroi,roilocation,angles,name,clims)
%generateActivityMovie This function generates a movie of the activity with the grid.
% Variables: img: movie stack (not dFoF, but bleach corrected)
                  %binarywhole = all ROIs represented as binary (active =
                  %1, non-active = 0
%                 postiveIndices = indices for all ROIs inside outlined
%                 region
%                 name = name of file to output
    if nargin < 6
            clims = [500 5000];
    end
    figure; imagesc(zeros(800,800)); colormap(gray); truesize;

    for i = 1:size(img,3)
        indx_green = find(thrroi(i,:)>=1);
        imagesc(img(:,:,i)); caxis(clims); hold on;
        %for j=1:size(positiveIndices,1)
        %plot(positiveIndices(j,1:2:end),positiveIndices(j,2:2:end),'Color','k');
        %end
        if ~isempty(indx_green)
            for j = 1:size(indx_green,2)
                temp = indx_green(j);
                drawellipse('Position',roilocation(temp,:),'SemiAxes',[1 1],'Color','g','InteractionsAllowed','none');
            end
        end
            M(i) = getframe;

        hold off;
    end

%write video
    v = VideoWriter([name '.mp4'],'MPEG-4');
    v.Quality = 100;

    v.FrameRate = 10;
    open(v);

    for i=1:size(M,2)
        writeVideo(v,M(i).cdata);
    end
    close(v);
end

